apiVersion: v1
kind: Secret
metadata:
  name: proyectify-secrets
  namespace: proyectify
type: Opaque
stringData:
  JWT_SECRET: change_me
  MONGO_URI: mongodb+srv://<user>:<pass>@<cluster>/<db>?retryWrites=true&w=majority
  RESEND_API_KEY: re_xxx
  RESEND_FROM: onboarding@resend.dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proyectify-config
  namespace: proyectify
data:
  NODE_ENV: production
  PORT: "5000"
  ENFORCE_HTTPS: "true"
  BCRYPT_ROUNDS: "12"
  NOTIFY_EMAIL_ON_ARTICLE: "true"
  GEMINI_MODEL_TEXT: gemini-2.5-flash
  GEMINI_MODEL_CHAT: gemini-2.5-flash

